version: '3'
name: tse_repo

services:
  mysql-master:
    image: mysql:8.0.34
    container_name: mysql-master
    restart: unless-stopped
    env_file: 
      - ./master/.env.master
    ports:
      - "3306:3306"
    volumes:
      - master-data:/var/lib/mysql
      - master-data-cnf:/etc/mysql/conf.d
      - ./master/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      backend:
        aliases:
          - mysql

volumes:
  master-data:
  master-data-cnf:

networks:
  backend:
    internal: false # change this to true later for deployment
