version: '3'
name: tse_repo

services:
  mysql-master:
    image: percona:ps-8.0
    container_name: mysql-master
    restart: unless-stopped
    env_file: 
      - ./master/.env.master
    cap_add:
      - all
    volumes:
      - master-data:/var/lib/mysql
      - master-data-cnf:/etc/my.cnf
    networks:
      backend:
        aliases:
          - mysql

volumes:
  master-data:
  master-data-cnf:

networks:
  backend:
    internal: true
