version: '3'
name: tse_repo
services:
  mysql-master:
    image: percona:ps-8.0
    container_name: mysql-master
    restart: unless-stopped
    env_file: 
      - ./master/.env.master
    cap_add:
      - all
    volumes:
      - master-data:/var/lib/mysql
    networks:
      backend:
        aliases:
          - mysql
          - mysql-master

  mysql-slave:
    image: percona:ps-8.0
    container_name: mysql-slave
    restart: unless-stopped
    env_file: ./slave/.env.slave
    cap_add:
      - all
    volumes:
      - slave-data:/var/lib/mysql
    networks:
      backend:
        aliases:
          - mysql
          - mysql-slave

volumes:
  master-data:
  slave-data:

networks:
  backend:
    internal: true
