---
name: Test Python Application and Build with BuildKit Cache
run-name: ${{ github.actor }} is testing the python application and building the image and pushing it on DockerHub.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  python-test:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pylint pytest
        if [ -f ./tse-repo-operations/python/requirements.txt ]; then pip install -r ./tse-repo-operations/python/requirements.txt; fi
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
    
  build-docker-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Docker build
        uses: docker/build-push-action@v4
        with:
          file: ./tse-repo-operations/Dockerfile
          context : ./tse-repo-operations
          push: ${{ github.event_name != 'pull_request' }}
          tags: amirstm/tse-repo-operations
          cache-from: type=gha
          cache-to: type=gha,mode=max
